import logging
import yaml
from pathlib import Path
from services.db_service import get_db_connection
from typing import List, Dict, Any

logger = logging.getLogger("AskLytics-Scout")

class ScoutAgent:
    """Autonomous agent for schema discovery and MDL generation."""
    
    def __init__(self, output_root: str = "semantic/mdl"):
        self.output_root = Path(output_root)
        self.output_root.mkdir(parents=True, exist_ok=True)

    def discover_and_generate(self, schema: str = "dbo") -> Dict[str, Any]:
        """Crawl the database and generate MDL files."""
        # TODO: Implement full crawler. For now, we'll demonstrate the core logic.
        logger.info(f"Starting discovery for schema: {schema}")
        
        try:
            with get_db_connection() as conn:
                cursor = conn.cursor()
                
                # 1. Fetch tables
                cursor.execute("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ?", (schema,))
                tables = [row[0] for row in cursor.fetchall()]
                
                for table in tables:
                    self._generate_entity_mdl(cursor, schema, table)
                    
                return {"status": "success", "tables_discovered": len(tables)}
        except Exception as e:
            logger.error(f"Discovery failed: {e}")
            return {"status": "error", "message": str(e)}

    def _generate_entity_mdl(self, cursor, schema, table):
        """Fetch columns and generate YAML entity file."""
        cursor.execute(
            "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS "
            "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?", (schema, table)
        )
        columns = []
        for row in cursor.fetchall():
            col_name = row[0]
            col_type = row[1]
            columns.append({
                "name": col_name,
                "type": col_type,
                "description": f"The {col_name} column from {table}."
            })

        # Discover outbound foreign keys
        cursor.execute(
            """
            SELECT
                cu.CONSTRAINT_NAME,
                cu.COLUMN_NAME AS fk_column,
                ku.TABLE_NAME AS pk_table,
                ku.COLUMN_NAME AS pk_column
            FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
            JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu
                ON rc.CONSTRAINT_NAME = cu.CONSTRAINT_NAME
            JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ku
                ON rc.UNIQUE_CONSTRAINT_NAME = ku.CONSTRAINT_NAME
            WHERE cu.TABLE_SCHEMA = ? AND ku.TABLE_SCHEMA = ? AND cu.TABLE_NAME = ?
            """,
            (schema, schema, table)
        )
        relationships = []
        for fk_name, fk_col, pk_table, pk_col in cursor.fetchall():
            relationships.append({
                "name": fk_name,
                "type": "many_to_one",
                "from": f"[{schema}].[{table}].[{fk_col}]",
                "to": f"[{schema}].[{pk_table}].[{pk_col}]"
            })
            
        entity_data = {
            "name": table,
            "description": f"Autogenerated entity for table {table}.",
            "reference": {"table": f"{schema}.{table}"},
            "columns": columns
        }

        if relationships:
            entity_data["relationships"] = relationships
        
        target_path = self.output_root / "entities" / f"{table}.yaml"
        target_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(target_path, "w", encoding="utf-8") as f:
            yaml.dump(entity_data, f)
            
        logger.info(f"Generated MDL for {table}")
